### ISSUE TITLE
Instrução para fazer o build do executável

### ISSUE THREAD

**Issue by jgrocha** [Klipperr/Cartografia#1]
Olá,

Este trabalho parece-me interessante. Quero experimentar. No entanto, não corre no meu Ubuntu :-(

Eu consigo correr o Unity (instalado a partir do [package .deb](http://beta.unity3d.com/download/fd37f3680b5f/unity-editor_amd64-2017.2.0b11.deb)).

Que instruções usam para o build em Windows, para eu tentar fazer o mesmo ou parecido no Ubuntu?

**Comment by ItsKlipper** [comment]
No windows basta abrir o executável e correr.
Sendo assim irá ser disponibilizado uma versao para correr em Ubuntu.

**Comment by ItsKlipper** [comment]
Já esta adicionado a versao para correr em ubuntu

**Comment by jgrocha** [comment]
Obrigado. De qualquer forma, preferia ver código e ter instruções de como se faz o build. Sem isso, não se pode "reproduzir" o trabalho nem podem receber contribuições e ideias de outros.
